"""Adiciona campos da Meta na tabela Barbearia

Revision ID: 8f8baec13496
Revises: edd120c8f194
Create Date: 2025-11-04 21:33:09.968754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f8baec13496'
down_revision = 'edd120c8f194'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_phone_number_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('meta_access_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearia', schema=None) as batch_op:
        batch_op.drop_column('meta_access_token')
        batch_op.drop_column('meta_phone_number_id')

    # ### end Alembic commands ###
