"""Alarga coluna meta_access_token para Text

Revision ID: c111b46dc006
Revises: 8f8baec13496
Create Date: 2025-11-06 21:18:07.249568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c111b46dc006'
down_revision = '8f8baec13496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearia', schema=None) as batch_op:
        batch_op.alter_column('meta_access_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barbearia', schema=None) as batch_op:
        batch_op.alter_column('meta_access_token',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
