"""Adiciona arquitetura multi-tenancy (Barbearia)

Revision ID: c4ba941c5b31
Revises: 01c2369f53c2
Create Date: 2025-10-22 20:26:49.874678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ba941c5b31'
down_revision = '01c2369f53c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barbearia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=100), nullable=False),
    sa.Column('telefone_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('status_assinatura', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefone_whatsapp')
    )
    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'barbearia', ['barbearia_id'], ['id'])

    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'barbearia', ['barbearia_id'], ['id'])

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'barbearia', ['barbearia_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('barbearia_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'barbearia', ['barbearia_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')
        batch_op.drop_column('role')

    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('profissional', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    with op.batch_alter_table('agendamento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('barbearia_id')

    op.drop_table('barbearia')
    # ### end Alembic commands ###
