"""Adiciona coluna preco para Servico

Revision ID: cf00bda7b735
Revises: 
Create Date: 2025-10-21 21:51:13.969144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf00bda7b735'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_start_time'))

    op.drop_table('appointments')
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico', schema=None) as batch_op:
        batch_op.drop_column('preco')

    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), nullable=False),
    sa.Column('phone', sa.VARCHAR(length=30), nullable=False),
    sa.Column('start_time', sa.DATETIME(), nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###
